"""Add dynamic form models

Revision ID: ea18dbb64a7e
Revises: 884c15be732a
Create Date: 2025-05-19 20:50:46.070798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea18dbb64a7e"
down_revision: Union[str, None] = "884c15be732a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=56), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["forms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "form_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["forms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "form_submission_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["form_fields.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["form_submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("form_submission_fields")
    op.drop_table("form_submissions")
    op.drop_table("form_fields")
    # ### end Alembic commands ###
