"""Add dynamic form models

Revision ID: 884c15be732a
Revises: 11ef4fe07f90
Create Date: 2025-05-19 20:45:06.895505

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "884c15be732a"
down_revision: Union[str, None] = "11ef4fe07f90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_input_fields")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_id", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("full_name", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("email", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("password", mysql.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table(
        "user_input_fields",
        sa.Column(
            "id",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("label", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("value", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="user_input_fields_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
